server_ip: "127.0.0.1:8080" # if running locally, also try "[::]:8080"
seed: 1
discount: 0.99
tau: 0.005
policy_noise_f: 0.2
noise_clip_f: 0.5
policy_freq: 2
alpha: 2.5
alpha_0: 1.0
alpha_1: 0.0
alpha_2: 1.0
batch_size: 256
decay_rate: 0.995
l_r: 0.0003
local_epochs: 20